name: manual release

on:
  workflow_dispatch

jobs:
  build-release:

    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master
        persist-credentials: false
    - name: JDK 8 Set
      uses: actions/setup-java@v1
      with: 
        java-version: 1.8
    - name: Maven Cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Maven deploy to sonatype for Scala 2.11
      uses: samuelmeuli/action-maven-publish@v1
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
        nexus_username: ${{ secrets.SONATYPE_USERNAME }}
        nexus_password: ${{ secrets.SONATYPE_PASSWORD }}
        maven_profiles: scala-2.11,release-sonatype
        maven_args: -B -DskipTests -f pom.xml

    - name: Maven deploy to sonatype for Scala 2.12
      uses: samuelmeuli/action-maven-publish@v1
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
        nexus_username: ${{ secrets.SONATYPE_USERNAME }}
        nexus_password: ${{ secrets.SONATYPE_PASSWORD }}
        maven_profiles: scala-2.12,release-sonatype
        maven_args: -B -DskipTests -f pom.xml

    - name: Maven deploy to sonatype for Scala 2.10
      uses: samuelmeuli/action-maven-publish@v1
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
        nexus_username: ${{ secrets.SONATYPE_USERNAME }}
        nexus_password: ${{ secrets.SONATYPE_PASSWORD }}
        maven_profiles: scala-2.10,release-sonatype
        maven_args: -B -DskipTests -f pom.xml