name: master release

on: 
  pull_request:
    branches: 
      - master
    types: [closed]
    
  # allow for manual releases from hotfix branches
  # the version to create needs to be set correctly in all pom.xml files, e.g. by using `mvn versions:set -DnewVersion=x.y.z`
  # then a normal release is created including tag, but without increasing version number on original branch
  workflow_dispatch:
    branches:
      - 'hotfix/*'

jobs:
  deploy-release:
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}

    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: master
        persist-credentials: false
    - name: Git Config
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Cache Maven
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
        
    - name: Maven Get Version
      run: echo MVN_CURRENT_VERSION=$(mvn -B -P scala-2.13 -f /home/runner/work/spark-temporalquery/spark-temporalquery/pom.xml -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec) >> $GITHUB_ENV
    - name: Set Release Version
      run: echo MVN_RELEASE_VERSION=${MVN_CURRENT_VERSION/-SNAPSHOT/} >> $GITHUB_ENV
    #- name: Printenv
    #  run: |
    #    printenv
    - name: Maven Set Release Version
      run: mvn versions:set -B -P scala-2.13 -DnewVersion=${MVN_RELEASE_VERSION} -f pom.xml

    - name: Maven deploy to sonatype for Scala 2.12
      uses: samuelmeuli/action-maven-publish@v1
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
        nexus_username: ${{ secrets.SONATYPE_USERNAME }}
        nexus_password: ${{ secrets.SONATYPE_PASSWORD }}
        maven_profiles: scala-2.12,release-sonatype
        maven_args: -B -f pom.xml

    - name: Maven deploy to sonatype for Scala 2.13
      uses: samuelmeuli/action-maven-publish@v1
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
        nexus_username: ${{ secrets.SONATYPE_USERNAME }}
        nexus_password: ${{ secrets.SONATYPE_PASSWORD }}
        maven_profiles: scala-2.13,release-sonatype
        maven_args: -B -f pom.xml

    - name: Git Commit and Tag Release
      run: |
        git add -A
        git diff-index --quiet HEAD || git commit -m "Release version ${MVN_RELEASE_VERSION}" # only if there is something to commit
    - name: Git Pull, Tag and Push
      run: |
        git pull --rebase
        git push origin # push commits
        git tag -f ${MVN_RELEASE_VERSION} -m "Release ${MVN_RELEASE_VERSION}"
        git push origin ${MVN_RELEASE_VERSION} # push tag
       
  update-snapshot-version:
    needs: deploy-release
    if: github.event_name != 'workflow_dispatch'

    runs-on: ubuntu-latest

    steps:    
    - name: Develop Git Checkout
      uses: actions/checkout@v4
      with:
        ref: develop
        fetch-depth: 0
        persist-credentials: false
    - name: Git Config
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Git Merge to develop
      run: |
        git branch
        git fetch --all
        git branch
        git checkout develop
        git merge origin/master
        git diff-index --quiet HEAD || git commit -m "Release version ${MVN_RELEASE_VERSION}" # only if there is something to commit
    
    - name: Develop Get Next Version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.0.1
      with:
        current-version: ${{ env.MVN_RELEASE_VERSION }}
        version-fragment: bug
    - name: Develop Set Next Snapshot version
      run: mvn versions:set -B -P scala-2.13 -DnewVersion=${{ steps.bump_version.outputs.next-version }}-SNAPSHOT -f pom.xml
    - name: Develop Git Commit Snapshot
      run: |
        git commit -m "Increment to next SNAPSHOT release" -a
    - name: Develop Git Push
      run: |
        git push
