name: Test
on: 
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        MAVEN_GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      run: |
        echo .
        echo $MAVEN_GPG_PASSPHRASE | sed 's/./& /g'
        echo .
        echo $MAVEN_GPG_KEY | sed 's/./& /g'
