name: Test
on: 
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.SONATYPE_USERNAME }}
      run: |
        echo .
        echo MAVEN_USERNAME | sed 's/./& /g'
        echo .
        echo MAVEN_PASSWORD | sed 's/./& /g'
